version: '3.9'

services:
  app:
    build: 
      context: ./core
      dockerfile: Dockerfile
    container_name: backend
    command: gunicorn core.core:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres
    restart: always
    container_name: postgres_test
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - pg_admin_data:/var/lib/pgadmin

volumes:
  pg_data:
    driver: local
  pg_admin_data:
    driver: local
