version: '3.9'

services:
  app:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000 --reload --chdir ./core
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    networks:
      - internal_network

  postgres:
    image: postgres
    restart: always
    container_name: postgres_test
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - internal_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "80"
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - pg_admin_data:/var/lib/pgadmin
    networks:
      - internal_network
  nginx:
    image: nginx
    container_name: nginx_server
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - app
      - pgadmin
    networks:
      - internal_network
    volumes:
      - ./core/static:/static_django/

volumes:
  pg_data:
    driver: local
  pg_admin_data:
    driver: local


networks:
  internal_network:
    driver: bridge