# Generated by Django 3.2.13 on 2022-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('unitary_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unitary value')),
                ('quantity_stock', models.IntegerField(verbose_name='Quantity in stock')),
                ('product_situation', models.CharField(choices=[('av', 'Available'), ('un', 'Unavailable')], max_length=2, verbose_name='Product situation')),
            ],
        ),
    ]
