# Generated by Django 3.2.13 on 2022-05-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unitary_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unitary value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order date')),
                ('applicant', models.CharField(max_length=150, verbose_name='Applicant')),
                ('zip_code', models.IntegerField(verbose_name='Zip code')),
                ('uf', models.CharField(max_length=2, verbose_name='Federation unity')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('number', models.IntegerField(verbose_name='Street')),
                ('forwarding_agent', models.CharField(max_length=200, verbose_name='Street')),
                ('order_situation', models.CharField(choices=[('p', 'Pending to send'), ('s', 'Sending'), ('d', 'Delivered')], max_length=1, verbose_name='Order situation')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product', verbose_name='Product')),
            ],
        ),
    ]
